#ifndef KC_Definitions_H
#define KC_Definitions_H

namespace KC {

#define nil nullptr
#define neg = -1

using Void = void;

using Bool = bool;

using Sym = char;

using Int = signed int;
using Int8 = signed char;
using Int16 = signed short int;
using Int32 = signed int;
using Int64 = signed long int;

using Nat = unsigned int;
using Nat8 = unsigned char;
using Nat16 = unsigned short int;
using Nat32 = unsigned int;
using Nat64 = unsigned long int;

using Real = double;
using Real32 = float;
using Real64 = double;

}

#endif // KC_Definitions_H
